---
image: registry.ddbuild.io/images/mirror/golang:1.23.4
variables:
  PROJECTNAME: "datadog-csi-driver"
  BUILD_DOCKER_REGISTRY: "registry.ddbuild.io/ci"
  JOB_DOCKER_IMAGE: "registry.ddbuild.io/ci-containers-project:v50051243-ace27e7-v1.22"
  PUBLIC_IMAGE_NAME: "csi-driver"
cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /go/pkg/mod

stages:
  - test
  - build_image
  - release

tests:
  stage: test
  image: registry.ddbuild.io/images/mirror/golang:1.23.4
  tags: ["arch:amd64"]
  script:
    - make test

build_image:
  stage: build_image
  tags:
    - "arch:amd64"
  image: $JOB_DOCKER_IMAGE
  variables:
    TARGET_IMAGE: $BUILD_DOCKER_REGISTRY/$PROJECTNAME:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    RELEASE_IMAGE: $BUILD_DOCKER_REGISTRY/$PROJECTNAME:$CI_COMMIT_TAG
  script:
    - IMG=$TARGET_IMAGE make docker-buildx-ci

publish_public_main:
  stage: release
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
    - when: never
  trigger:
    project: DataDog/public-images
    branch: main
    strategy: depend
  variables:
    IMG_SOURCES: $BUILD_DOCKER_REGISTRY/$PROJECTNAME:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    IMG_DESTINATIONS: $PUBLIC_IMAGE_NAME:main,$PUBLIC_IMAGE_NAME:${CI_COMMIT_SHA}
    IMG_SIGNING: "false"

publish_public_tag:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
    - when: never
  trigger:
    project: DataDog/public-images
    branch: main
    strategy: depend
  variables:
    IMG_SOURCES: $BUILD_DOCKER_REGISTRY/$PROJECTNAME:$CI_COMMIT_TAG
    IMG_DESTINATIONS: $PUBLIC_IMAGE_NAME:$CI_COMMIT_TAG
    IMG_SIGNING: "false"

publish_public_latest:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
    - when: never
  trigger:
    project: DataDog/public-images
    branch: main
    strategy: depend
  variables:
    IMG_SOURCES: $BUILD_DOCKER_REGISTRY/$PROJECTNAME:$CI_COMMIT_TAG
    IMG_DESTINATIONS: $PUBLIC_IMAGE_NAME:latest
    IMG_SIGNING: "false"

trigger_internal_image:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
    - when: never
  trigger:
    project: DataDog/images
    branch: master
    strategy: depend
  variables:
    IMAGE_VERSION: tmpl-v1
    IMAGE_NAME: $PROJECTNAME
    RELEASE_TAG: ${CI_COMMIT_REF_SLUG}
    BUILD_TAG: ${CI_COMMIT_REF_SLUG}
    TMPL_SRC_IMAGE: v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    RELEASE_STAGING: "true"
    RELEASE_PROD: "true"
