---
image: registry.ddbuild.io/images/mirror/golang:1.23.4
variables:
  PROJECTNAME: "datadog-csi-driver"
  TARGET_TAG: v$CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA
  BUILD_DOCKER_REGISTRY: "registry.ddbuild.io/ci"
  JOB_DOCKER_IMAGE: "registry.ddbuild.io/ci-containers-project:v50051243-ace27e7-v1.22"
  DOCKER_REGISTRY_LOGIN_SSM_KEY: docker_hub_login
  DOCKER_REGISTRY_PWD_SSM_KEY: docker_hub_pwd
  DOCKER_REGISTRY_URL: docker.io
cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /go/pkg/mod

stages:
  - test
  - build_image

tests:
  stage: test
  image: registry.ddbuild.io/images/mirror/golang:1.23.4
  tags: ["arch:amd64"]
  script:
    - go test -v ./...

build_image:
  stage: build_image
  tags:
    - "arch:amd64"
  image: $JOB_DOCKER_IMAGE
  variables:
    TARGET_IMAGE: $BUILD_DOCKER_REGISTRY/$PROJECTNAME:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    RELEASE_IMAGE: $BUILD_DOCKER_REGISTRY/$PROJECTNAME:$CI_COMMIT_TAG
  script: |-
    IMG=$TARGET_IMAGE \
    docker buildx build . \
    --build-arg LDFLAGS="${LDFLAGS}" \
    --platform=linux/arm64,linux/amd64 \
    --label target=build \
    --push \
    --tag ${TARGET_IMAGE} ${RELEASE_IMAGE_TAG}
