apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dd-csi-node-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: dd-csi-node-server
  template:
    metadata:
      labels:
        app: dd-csi-node-server
    spec:
      hostNetwork: true
      containers:
        - name: csi-node-driver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.pullSecrets }}
          imagePullSecrets:
    {{ toYaml .Values.image.pullSecrets | indent 8 }}
          {{- end }}
          args:
            - /dd-csi-driver
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        - name: csi-node-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
          args:
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/datadog.csi/driver/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi # Match this to ADDRESS
            - name: registration-dir
              mountPath: /registration # This is where the registrar writes the registration information
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/datadog.csi/driver
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
